### ISSUE TITLE
boost_1_70_0.tar.gz is Forbidden

### ISSUE THREAD

**Issue by sl84702** [boostorg/boost#299] opened 2019-05-30 12:26 UTC
wget https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz
--2019-05-30 15:24:16--  https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz
Resolving dl.bintray.com (dl.bintray.com)... 54.93.138.218, 35.157.207.108
Connecting to dl.bintray.com (dl.bintray.com)|54.93.138.218|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-05-30 15:24:17 ERROR 403: Forbidden.

error: downloading 'https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 54.93.138.218...

  TCP_NODELAY set

  Connected to dl.bintray.com (54.93.138.218) port 443 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /etc/ssl/cert.pem
    CApath: none

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [217 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [89 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [3593 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [333 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Client hello (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  TLSv1.2 (IN), TLS change cipher, Client hello (1):

  [1 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256

  ALPN, server did not agree to a protocol

  Server certificate:

   subject: CN=*.bintray.com
   start date: Sep 15 00:00:00 2018 GMT
   expire date: Nov  9 12:00:00 2019 GMT
   subjectAltName: host "dl.bintray.com" matched cert's "*.bintray.com"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust RSA CA 2018
   SSL certificate verify ok.

  GET /boostorg/release/1.70.0/source/boost_1_70_0.tar.gz HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.54.0

  Accept: */*

  The requested URL returned error: 403 Forbidden

  stopped the pause stream!

  Closing connection 0

  TLSv1.2 (OUT), TLS alert, Client hello (1):

  [2 bytes data]

         --- LOG END ---
         error: downloading 'https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 54.93.138.218...

  TCP_NODELAY set

  Connected to dl.bintray.com (54.93.138.218) port 443 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /etc/ssl/cert.pem
    CApath: none

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [217 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [89 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [3593 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [333 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Client hello (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  TLSv1.2 (IN), TLS change cipher, Client hello (1):

  [1 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256

  ALPN, server did not agree to a protocol

  Server certificate:

   subject: CN=*.bintray.com
   start date: Sep 15 00:00:00 2018 GMT
   expire date: Nov  9 12:00:00 2019 GMT
   subjectAltName: host "dl.bintray.com" matched cert's "*.bintray.com"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust RSA CA 2018
   SSL certificate verify ok.

  GET /boostorg/release/1.70.0/source/boost_1_70_0.tar.gz HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.54.0

  Accept: */*

  The requested URL returned error: 403 Forbidden

  stopped the pause stream!

  Closing connection 0

  TLSv1.2 (OUT), TLS alert, Client hello (1):

  [2 bytes data]

         --- LOG END ---
         error: downloading 'https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 54.93.138.218...

  TCP_NODELAY set

  Connected to dl.bintray.com (54.93.138.218) port 443 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /etc/ssl/cert.pem
    CApath: none

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [217 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [89 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [3593 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [333 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Client hello (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  TLSv1.2 (IN), TLS change cipher, Client hello (1):

  [1 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256

  ALPN, server did not agree to a protocol

  Server certificate:

   subject: CN=*.bintray.com
   start date: Sep 15 00:00:00 2018 GMT
   expire date: Nov  9 12:00:00 2019 GMT
   subjectAltName: host "dl.bintray.com" matched cert's "*.bintray.com"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust RSA CA 2018
   SSL certificate verify ok.

  GET /boostorg/release/1.70.0/source/boost_1_70_0.tar.gz HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.54.0

  Accept: */*

  The requested URL returned error: 403 Forbidden

  stopped the pause stream!

  Closing connection 0

  TLSv1.2 (OUT), TLS alert, Client hello (1):

  [2 bytes data]

         --- LOG END ---
         error: downloading 'https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 54.93.138.218...

  TCP_NODELAY set

  Connected to dl.bintray.com (54.93.138.218) port 443 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /etc/ssl/cert.pem
    CApath: none

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [217 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [89 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [3593 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [333 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Client hello (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  TLSv1.2 (IN), TLS change cipher, Client hello (1):

  [1 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256

  ALPN, server did not agree to a protocol

  Server certificate:

   subject: CN=*.bintray.com
   start date: Sep 15 00:00:00 2018 GMT
   expire date: Nov  9 12:00:00 2019 GMT
   subjectAltName: host "dl.bintray.com" matched cert's "*.bintray.com"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust RSA CA 2018
   SSL certificate verify ok.

  GET /boostorg/release/1.70.0/source/boost_1_70_0.tar.gz HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.54.0

  Accept: */*

  The requested URL returned error: 403 Forbidden

  stopped the pause stream!

  Closing connection 0

  TLSv1.2 (OUT), TLS alert, Client hello (1):

  [2 bytes data]

         --- LOG END ---
         error: downloading 'https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 54.93.138.218...

  TCP_NODELAY set

  Connected to dl.bintray.com (54.93.138.218) port 443 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /etc/ssl/cert.pem
    CApath: none

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [217 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [89 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [3593 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [333 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Client hello (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  TLSv1.2 (IN), TLS change cipher, Client hello (1):

  [1 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256

  ALPN, server did not agree to a protocol

  Server certificate:

   subject: CN=*.bintray.com
   start date: Sep 15 00:00:00 2018 GMT
   expire date: Nov  9 12:00:00 2019 GMT
   subjectAltName: host "dl.bintray.com" matched cert's "*.bintray.com"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust RSA CA 2018
   SSL certificate verify ok.

  GET /boostorg/release/1.70.0/source/boost_1_70_0.tar.gz HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.54.0

  Accept: */*

  The requested URL returned error: 403 Forbidden

  stopped the pause stream!

  Closing connection 0

  TLSv1.2 (OUT), TLS alert, Client hello (1):

  [2 bytes data]

         --- LOG END ---
         error: downloading 'https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz' failed
         status_code: 22
         status_string: "HTTP response code said error"
         log:
         --- LOG BEGIN ---
           Trying 54.93.138.218...

  TCP_NODELAY set

  Connected to dl.bintray.com (54.93.138.218) port 443 (#0)

  ALPN, offering http/1.1

  Cipher selection:
  ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH

  successfully set certificate verify locations:

    CAfile: /etc/ssl/cert.pem
    CApath: none

  TLSv1.2 (OUT), TLS handshake, Client hello (1):

  [217 bytes data]

  TLSv1.2 (IN), TLS handshake, Server hello (2):

  [89 bytes data]

  TLSv1.2 (IN), TLS handshake, Certificate (11):

  [3593 bytes data]

  TLSv1.2 (IN), TLS handshake, Server key exchange (12):

  [333 bytes data]

  TLSv1.2 (IN), TLS handshake, Server finished (14):

  [4 bytes data]

  TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

  [70 bytes data]

  TLSv1.2 (OUT), TLS change cipher, Client hello (1):

  [1 bytes data]

  TLSv1.2 (OUT), TLS handshake, Finished (20):

  [16 bytes data]

  TLSv1.2 (IN), TLS change cipher, Client hello (1):

  [1 bytes data]

  TLSv1.2 (IN), TLS handshake, Finished (20):

  [16 bytes data]

  SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256

  ALPN, server did not agree to a protocol

  Server certificate:

   subject: CN=*.bintray.com
   start date: Sep 15 00:00:00 2018 GMT
   expire date: Nov  9 12:00:00 2019 GMT
   subjectAltName: host "dl.bintray.com" matched cert's "*.bintray.com"
   issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=GeoTrust RSA CA 2018
   SSL certificate verify ok.

  GET /boostorg/release/1.70.0/source/boost_1_70_0.tar.gz HTTP/1.1

  Host: dl.bintray.com

  User-Agent: curl/7.54.0

  Accept: */*

  The requested URL returned error: 403 Forbidden

  stopped the pause stream!

  Closing connection 0

  TLSv1.2 (OUT), TLS alert, Client hello (1):

  [2 bytes data]

         --- LOG END ---

**Comment by bbaassssiiee** [comment] 2019-05-30 13:43
When I try to download the checksum data I also get Forbidden!

[https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz.json](https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz.json)

**Comment by mclow** [comment] 2019-05-30 20:40
Should be fixed now.

**Closed by mclow** 2019-05-30 20:40 UTC

**Comment by bbaassssiiee** [comment] 2019-05-30 20:42
Confirmed.

**Comment by awmanoj** [comment] 2020-02-29 02:06
I've the exact same problem now. Any help?

**Comment by awmanoj** [comment] 2020-02-29 02:06
https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_67_0.tar.gz 

Leads to 403, "Forbidden!"

**Comment by Mystfit** [comment] 2020-02-29 04:48
I have the same problem as well. I can't download 1.70 or 1.72.

**Comment by jjYBdx4IL** [comment] 2020-02-29 15:35
me neither.

**Comment by jjYBdx4IL** [comment] 2020-02-29 15:35
how about setting up a nagios check or something? xd

**Comment by jabaa** [comment] 2020-02-29 22:02
The conan package uses tries to download https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2 and breaks with Forbidden

**Comment by mclow** [comment] 2020-03-01 07:02
We have reached our bandwidth limit at bintray for the month.
Try again tomorrow (3/1).

**Comment by Weiming-Hu** [comment] 2020-03-01 13:45
I still have the problem for downloading. Thanks.

**Comment by jabaa** [comment] 2020-03-01 20:38
@mclow The problem is still there. Try it yourself: https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2

**Comment by aleksa2808** [comment] 2020-03-27 21:02
Happening right now as well.

**Comment by Weiming-Hu** [comment] 2020-03-27 21:35
Confirmed here as well.

LOL. Apparently Boost is becoming more and more popular and so many people are downloading it. Mission

**Comment by mclow** [comment] 2020-03-27 22:26
We get a certain # of GB of bandwidth from BinTray each month. In both Feb and March, we reached that limit about the 27th of the month.  If we aren't able to address this, everything will start working again on the 1st.

**Comment by wilhelmy** [comment] 2020-03-28 12:56
How about introducing a mirror.boost.org subdomain that redirects to a bunch of mirrors in a round-robin kind of way?

**Comment by mclow** [comment] 2020-03-28 15:28
The problem is not the reliability of the servers. The problem is that we have a large, but limited amount of (donated) bandwidth (about 30 TB/month).  Someone could set up a set of mirrors, but who is going to provide (pay for) the service?

**Comment by Weiming-Hu** [comment] 2020-03-28 15:46
Hi @mclow, thank you for the reply. First of all, I really appreciate the work dedicated to Boost making it a powerful and, as we are pretty sure now, a popular library. I'm a Ph.D. student and I'm using Boost quite often. I also appreciate its open-source nature.

I have a suggestion that, instead of paying for extra service, given the financial limit, why not try to educate (in a nice way of course 😄) other developers? For example,

- encouraging developers to have a local copy and not to download boost every time when they need it;
- pointing out some other good and trusted sources of mirrors for alternatives;
- having a real-time count to show how far the download limit is on your website;

I guess my point is that users of Boost should be aware of this potential problem so that they will take this into account when designing their own libraries/packages that depend on Boost.

Thank you.

**Comment by xkszltl** [comment] 2020-03-28 23:40
Bintray seems to have free 1TB/month for open source project.
Is that possible to setup a list of mirror accounts and do HTTP302 for round-robin?

**Comment by wilhelmy** [comment] 2020-03-29 14:52
> The problem is not the reliability of the servers. The problem is that we have a large, but limited amount of (donated) bandwidth (about 30 TB/month). Someone could set up a set of mirrors, but who is going to provide (pay for) the service?

Reliability aside (which is besides the point here) distributing the load over several mirrors would decrease the bandwidth on each particular service, and thus allow staying below the quota. 

Possible options for services mirroring FOSS software for free include sourceforge as well as sites like https://osuosl.org/services/hosting/ as well as several other universities and institutions supporting free software. This may seem very 90s to you, but I guess it would work. I can dig up more potential mirrors if you're interested at all.

**Comment by alphamarket** [comment] 2020-03-30 06:09
This problem is happening now, I cannot download anything under https://dl.bintray.com/boostorg/ but the folders are getting opened. I need to download the boost now!

**Comment by tt4g** [comment] 2020-03-30 06:34
@alphamarket You can get boost from SourceForge: https://sourceforge.net/projects/boost/files/boost/

**Comment by bb-dsa** [comment] 2020-03-30 07:08
> @alphamarket You can get boost from SourceForge: https://sourceforge.net/projects/boost/files/boost/

Unfortunately this mirror does not serve 1.71.0 which I have to use. Having incomplete mirrors does not make it reliable.

**Comment by xkszltl** [comment] 2020-03-30 11:14
@alphamarket I understand your feelings. I'm not a boostorg maintainer but IMHO I would say the word you're using is a little bit too harsh. Keep in mind that people usually work for open source projects for free, and machine resources like network/storage are often donated.

**Comment by dtsmith2001** [comment] 2020-03-30 13:01
@bb-dsa try https://sourceforge.net/projects/boost/files/boost/1.72.0/

**Comment by dtsmith2001** [comment] 2020-03-30 13:10
I now have a local copy which I COPY into a Docker image. Our development team can obtain the built source from that image when they start the container.

**Comment by cde3535** [comment] 2021-05-04 21:36
Two days ago I was able to download boost with the dlbinary link(  https://dl.bintray.com/boostorg/ )but now its says forbidden why so?

**Comment by mclow** [comment] 2021-05-05 02:58
Because JFrog has shut down Bintray.
The new links (posted on the web site, and sent to the mailing list multiple times) are https://boostorg.jfrog.io/artifactory/main/release/

**Comment by xkszltl** [comment] 2021-05-05 17:51
Regarding that move.....On https://www.boost.org I saw:
<img width="262" alt="image" src="https://user-images.githubusercontent.com/5203025/117186444-68bda900-ae0d-11eb-825d-d29c097a8593.png">

Maybe I need a little bit more sleep -_-|||

**Comment by mclow** [comment] 2021-05-05 18:48
Ok, that (the date) is just wrong.  Thanks for the heads up.

**Comment by mclow** [comment] 2021-05-05 18:49
But if you read that article, you'll see:

> The service that Boost uses to serve up its releases, Bintray.com is being retired by JFrog on the 1st of May. Fortunately for Boost, they have a new service, called JFrog.Arifactory, which we have transitioned to.

**Comment by wilhelmy** [comment] 2021-05-05 20:20
Any reason against using https://osuosl.org/services/hosting/ as a mirror?
