### ISSUE TITLE
Build failed with Clang 16.0.0

### ISSUE THREAD

**Issue by DevTester888** [boostorg/boost#857] opened 2024-02-02 03:12 UTC
I get an build error. The log message is "integer value -1 is outside the valid range of values [0, 3] for this enumeration type" in integral_wrapper.hpp. This is a new clang feature, https://releases.llvm.org/16.0.0/tools/clang/docs/ReleaseNotes.html#id87 .
Has any idea for this issue? Please help me, thanks.

<img width="1385" alt="boost_build_error" src="https://github.com/boostorg/boost/assets/142870018/ee7c1cd4-53ce-43e5-824f-789bbc6c5228">

**Comment by pavel-trafimuk** [comment] 2024-02-29 09:31
Have the same issue

**Comment by haronaut** [comment] 2024-03-20 07:28
same here clang 18

**Comment by mclow** [comment] 2024-03-20 13:49
This is a duplicate of https://github.com/boostorg/mpl/issues/69

**Closed by mclow** 2024-03-20 13:49 UTC
